## socialfetch — Homebrew formula
##
## Regenerated by `make brew-update` after each GitHub release. Copy
## this file into the jedi4ever/homebrew-socialfetch tap repository as
## `Formula/socialfetch.rb` to publish a new version.
##
## Tap setup (one-time, on the maintainer's side):
##   1. Create an empty repo at https://github.com/jedi4ever/homebrew-socialfetch
##   2. mkdir Formula && cp <this file> Formula/socialfetch.rb
##   3. git add Formula/socialfetch.rb && git commit -m "socialfetch <version>" && git push
##
## End-user install (works once the tap repo above exists):
##   brew install jedi4ever/socialfetch/socialfetch
##
## or:
##   brew tap jedi4ever/socialfetch
##   brew install socialfetch
class Socialfetch < Formula
  desc "Toolkit that lets AI agents read and reason over the social web"
  homepage "https://github.com/jedi4ever/socialfetch"
  license "MIT"
  version "0.9.1"

  on_macos do
    on_arm do
      url "https://github.com/jedi4ever/socialfetch/releases/download/v0.9.1/socialfetch-0.9.1-darwin-arm64.tar.gz"
      sha256 "2ab488b5d51519ed6c66c0c0568e9441c5cd854d0fa92aa3e2f5ef6bbc561187"
    end
    on_intel do
      url "https://github.com/jedi4ever/socialfetch/releases/download/v0.9.1/socialfetch-0.9.1-darwin-amd64.tar.gz"
      sha256 "b44aabf536cddd449a21c04596313b6cbc97988b9449e8e36878262b102a8a5c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jedi4ever/socialfetch/releases/download/v0.9.1/socialfetch-0.9.1-linux-amd64.tar.gz"
      sha256 "199e3b3fb933e7d71e970f0e2f94c697f25532738888718ae8dde67ce5d2bea5"
    end
  end

  def install
    bin.install "socialfetch"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/socialfetch version")
  end
end
