#!/usr/bin/env bash
# brew-update.sh — regenerate homebrew/socialfetch.rb from the latest
# GitHub release. The release workflow (.github/workflows/release.yml)
# publishes three tarballs per tag — darwin-arm64, darwin-amd64,
# linux-amd64 — and this script SHA-256s each one and writes the
# values into the Homebrew formula in homebrew/socialfetch.rb.
#
# Run after publishing a release:
#   make build            # so socialfetch version reports the right value
#   git push --tags       # triggers .github/workflows/release.yml
#   # wait for the release workflow to finish + assets to upload
#   make brew-update      # regenerates homebrew/socialfetch.rb
#
# Then copy homebrew/socialfetch.rb into the jedi4ever/homebrew-socialfetch
# tap repo as Formula/socialfetch.rb and push.
#
# Optional: pass an explicit version as $1 to skip the local-binary
# version probe (useful when regenerating the formula for an older tag
# without rebuilding the binary):
#   scripts/brew-update.sh 0.9.0
set -euo pipefail

VERSION="${1:-}"
if [[ -z "$VERSION" ]]; then
  if [[ ! -x ./dist/socialfetch ]]; then
    echo "brew-update: ./dist/socialfetch missing — run 'make build' first" >&2
    exit 1
  fi
  VERSION=$(./dist/socialfetch version | awk '{print $2}')
fi

if [[ -z "$VERSION" ]]; then
  echo "brew-update: could not determine version" >&2
  exit 1
fi

BASE="https://github.com/jedi4ever/socialfetch/releases/download/v${VERSION}"

# sha downloads a tarball and prints its sha256. Fails loudly if the
# asset is missing — that's almost always "the release workflow hasn't
# uploaded yet" and the maintainer should wait + retry, not paper over.
sha() {
  local url="$1"
  curl --fail --silent --show-error --location "$url" | shasum -a 256 | awk '{print $1}'
}

echo "brew-update: hashing release assets for v${VERSION}…"
DARWIN_ARM64_SHA=$(sha "${BASE}/socialfetch-${VERSION}-darwin-arm64.tar.gz")
DARWIN_AMD64_SHA=$(sha "${BASE}/socialfetch-${VERSION}-darwin-amd64.tar.gz")
LINUX_AMD64_SHA=$(sha "${BASE}/socialfetch-${VERSION}-linux-amd64.tar.gz")

mkdir -p homebrew
cat > homebrew/socialfetch.rb <<EOF
## socialfetch — Homebrew formula
##
## Regenerated by \`make brew-update\` after each GitHub release. Copy
## this file into the jedi4ever/homebrew-socialfetch tap repository as
## \`Formula/socialfetch.rb\` to publish a new version.
##
## Tap setup (one-time, on the maintainer's side):
##   1. Create an empty repo at https://github.com/jedi4ever/homebrew-socialfetch
##   2. mkdir Formula && cp <this file> Formula/socialfetch.rb
##   3. git add Formula/socialfetch.rb && git commit -m "socialfetch <version>" && git push
##
## End-user install (works once the tap repo above exists):
##   brew install jedi4ever/socialfetch/socialfetch
##
## or:
##   brew tap jedi4ever/socialfetch
##   brew install socialfetch
class Socialfetch < Formula
  desc "Toolkit that lets AI agents read and reason over the social web"
  homepage "https://github.com/jedi4ever/socialfetch"
  license "MIT"
  version "${VERSION}"

  on_macos do
    on_arm do
      url "${BASE}/socialfetch-${VERSION}-darwin-arm64.tar.gz"
      sha256 "${DARWIN_ARM64_SHA}"
    end
    on_intel do
      url "${BASE}/socialfetch-${VERSION}-darwin-amd64.tar.gz"
      sha256 "${DARWIN_AMD64_SHA}"
    end
  end

  on_linux do
    on_intel do
      url "${BASE}/socialfetch-${VERSION}-linux-amd64.tar.gz"
      sha256 "${LINUX_AMD64_SHA}"
    end
  end

  def install
    bin.install "socialfetch"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/socialfetch version")
  end
end
EOF

echo "brew-update: wrote homebrew/socialfetch.rb (v${VERSION})"
echo "brew-update: next step — copy into jedi4ever/homebrew-socialfetch as Formula/socialfetch.rb and push"
